### PR TITLE
Implemented some more features for bad variable names

### PR DESCRIPTION
**Pull request by purag**
We can now catch:
- 1- or multi-dimensional arrays, as long as the array syntax is attached to the type name<br>(i.e. `Integer[][] someArray;`)
- single-character variable names followed by 0 or more digits
- variables create in a foreach loop (i.e. `for(Integer i : someArray)`)

### CODE REVIEW

**Comment by anikan** [comment]
Good. Note: multiple bad variables in a single line count as a single bad variable name. That should be fine though.

**Comment by purag** [comment]
grep is line by line, may not be able to account for that unless we use a smarter command. Any suggestions?

**Comment by purag** [comment]
Could also say "x lines with bad variable names" instead of "x bad variable names."

**Comment by anikan** [comment]
Oh for number of names, I grepped -on and piped to wc -l. Each match takes a different line so it works out. Not sure if it's entirely necessary though, I think "x lines" is more useful.

**Pull request merged**
